### ISSUE TITLE
Minor optimizations - use stringBuffer and consts

### ISSUE THREAD

**Issue by joaovperin** [aqeelshamz/rot13#1]
Hello. I have some tips for a little performance boost.

You can declare your map as a const so it can be resolved in compilation time, ensuring some performance optimization.

Also, you can use StringBuffer for appending the string, instead of just appending the string with += operator. So the runtime will not have to allocate strings on memory for every character and can just append them on the internal in-memory char array.

You can also create unit tests to ensure it'll be working forever.

**Comment by aqeelshamz** [comment]
Thanks
